backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "numeros"
    label: "Números Ganadores"
    files:
      - file: "data/numeros.json"
        label: "Resultados"
        name: "resultados"
        fields:
          - { label: "Día", name: "day", widget: "string" }
          - { label: "Noche", name: "night", widget: "string" }
          
